# Generated by Django 4.1.4 on 2022-12-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monopolyapp', '0002_gameinstance_rounds_gameinstance_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinstance',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monopolyapp', to=settings.AUTH_USER_MODEL),
        ),
    ]
